<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TehsilsUpTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // Fetch district IDs for Uttar Pradesh
        $districts = DB::table('districts')->pluck('id', 'name')->toArray();

        $tehsils = [
            'Unknown' => [
                ['id' => 1, 'name' => 'Unknown'],
            ],
            'Agra' => [
                ['id' => 2, 'name' => 'Agra'],
                ['id' => 3, 'name' => 'Fatehabad'],
                ['id' => 4, 'name' => 'Etmadpur'],
                ['id' => 5, 'name' => 'Kirawali'],
                ['id' => 6, 'name' => 'Bah'],
                ['id' => 7, 'name' => 'Kheragarh'],

            ],
            'Aligarh' => [
                ['id' => 9, 'name' => 'Koil'],
                ['id' => 10, 'name' => 'Iglas'],
                ['id' => 11, 'name' => 'Khair'],
                ['id' => 12, 'name' => 'Atrauli'],
                ['id' => 13, 'name' => 'Gabhana'],
            ],
            'Ambedkar Nagar' => [
                ['id' => 19, 'name' => 'Ambedkar Nagar'],
                ['id' => 20, 'name' => 'Akbarpur'],
                ['id' => 21, 'name' => 'Baskhari'],
                ['id' => 22, 'name' => 'Bhitri'],
                ['id' => 23, 'name' => 'Kadipur'],
                ['id' => 24, 'name' => 'Jalalpur'],
                ['id' => 25, 'name' => 'Maya Bazar'],
                ['id' => 26, 'name' => 'Ramnagar'],
            ],
            'Amroha' => [
                ['id' => 27, 'name' => 'Amroha'],
                ['id' => 28, 'name' => 'Dhanaura'],
                ['id' => 29, 'name' => 'Hasanpur'],
                ['id' => 30, 'name' => 'Joya'],
                ['id' => 31, 'name' => 'Gajraula'],
                ['id' => 32, 'name' => 'Sambhal'],
                ['id' => 33, 'name' => 'Muradabad'],
            ],
            'Auraiya' => [
                ['id' => 34, 'name' => 'Auraiya'],
                ['id' => 35, 'name' => 'Bidhuna'],
                ['id' => 36, 'name' => 'Etawah'],
                ['id' => 37, 'name' => 'Jaswantnagar'],
                ['id' => 38, 'name' => 'Saifai'],
                ['id' => 39, 'name' => 'Ajitmal'],
            ],
            'Azamgarh' => [
                ['id' => 40, 'name' => 'Azamgarh'],
                ['id' => 41, 'name' => 'Mubarakpur'],
                ['id' => 42, 'name' => 'Mehnagar'],
                ['id' => 43, 'name' => 'Tarwa'],
                ['id' => 44, 'name' => 'Jahangirganj'],
                ['id' => 45, 'name' => 'Sagri'],
                ['id' => 46, 'name' => 'Rani Ki Sarai'],
            ],
            'Bahraich' => [
                ['id' => 47, 'name' => 'Bahraich'],
                ['id' => 48, 'name' => 'Nanpara'],
                ['id' => 49, 'name' => 'Kaisarganj'],
                ['id' => 50, 'name' => 'Bhinga'],
                ['id' => 51, 'name' => 'Shrawasti'],
                ['id' => 52, 'name' => 'Risia'],
                ['id' => 53, 'name' => 'Balha'],
                ['id' => 54, 'name' => 'Brijmanganj'],
            ],
            'Ballia' => [
                ['id' => 55, 'name' => 'Ballia'],
                ['id' => 56, 'name' => 'Bansdih'],
                ['id' => 57, 'name' => 'Belthara Road'],
                ['id' => 58, 'name' => 'Rasra'],
                ['id' => 59, 'name' => 'Sikanderpur'],
                ['id' => 60, 'name' => 'Dubhar'],
                ['id' => 61, 'name' => 'Khandwa'],
                ['id' => 62, 'name' => 'Sahatwar'],
            ],
            'Banda' => [
                ['id' => 63, 'name' => 'Banda'],
                ['id' => 64, 'name' => 'Baberu'],
                ['id' => 65, 'name' => 'Bisanda'],
                ['id' => 66, 'name' => 'Mahuwa'],
                ['id' => 67, 'name' => 'Naraini'],
                ['id' => 68, 'name' => 'Tindwari'],
                ['id' => 69, 'name' => 'Patbundh'],
            ],
            'Barabanki' => [
                ['id' => 70, 'name' => 'Barabanki'],
                ['id' => 71, 'name' => 'Ramnagar'],
                ['id' => 72, 'name' => 'Haidergarh'],
                ['id' => 73, 'name' => 'Zaidpur'],
                ['id' => 74, 'name' => 'Nawabganj'],
                ['id' => 75, 'name' => 'Banki'],
                ['id' => 76, 'name' => 'Dewa'],
            ],
            'Bareilly' => [
                ['id' => 77, 'name' => 'Bareilly'],
                ['id' => 78, 'name' => 'Bhojipura'],
                ['id' => 79, 'name' => 'Faridpur'],
                ['id' => 80, 'name' => 'Rudrapur'],
                ['id' => 81, 'name' => 'Aonla'],
                ['id' => 82, 'name' => 'Bithiri Chainpur'],
                ['id' => 83, 'name' => 'Pilgrim'],
            ],
            'Basti' => [
                ['id' => 84, 'name' => 'Basti'],
                ['id' => 85, 'name' => 'Kaptanganj'],
                ['id' => 86, 'name' => 'Rudauli'],
                ['id' => 87, 'name' => 'Sadar'],
                ['id' => 88, 'name' => 'Harraiya'],
                ['id' => 89, 'name' => 'Saltauwa'],
                ['id' => 90, 'name' => 'Mankapur'],
            ],
            'Bhadohi' => [
                ['id' => 91, 'name' => 'Bhadohi'],
                ['id' => 92, 'name' => 'Gyanpur'],
                ['id' => 93, 'name' => 'Aurai'],
                ['id' => 94, 'name' => 'Suriyavan'],
                ['id' => 95, 'name' => 'Kachhawan'],
            ],
            'Chandauli' => [
                ['id' => 96, 'name' => 'Chandauli'],
                ['id' => 97, 'name' => 'Sakaldiha'],
                ['id' => 98, 'name' => 'Naugarh'],
                ['id' => 99, 'name' => 'Mughalsarai'],
                ['id' => 100, 'name' => 'Kachhwa'],
                ['id' => 101, 'name' => 'Chahaniya'],
                ['id' => 102, 'name' => 'Buxwaha'],
            ],
            'Deoria' => [
                ['id' => 103, 'name' => 'Deoria'],
                ['id' => 104, 'name' => 'Bhatni'],
                ['id' => 105, 'name' => 'Salempur'],
                ['id' => 106, 'name' => 'Rudrapur'],
                ['id' => 107, 'name' => 'Tarkulha'],
                ['id' => 108, 'name' => 'Kushi Nagar'],
            ],
            'Etah' => [
                ['id' => 109, 'name' => 'Etah'],
                ['id' => 110, 'name' => 'Aliganj'],
                ['id' => 111, 'name' => 'Kasganj'],
                ['id' => 112, 'name' => 'Patiyali'],
                ['id' => 113, 'name' => 'Jaithara'],
                ['id' => 114, 'name' => 'Sakit'],
            ],
            'Etawah' => [
                ['id' => 115, 'name' => 'Etawah'],
                ['id' => 116, 'name' => 'Saifai'],
                ['id' => 117, 'name' => 'Bharthana'],
                ['id' => 118, 'name' => 'Jaswantnagar'],
                ['id' => 119, 'name' => 'Ekdil'],
                ['id' => 120, 'name' => 'Gopamau'],
            ],
            'Faizabad' => [
                ['id' => 121, 'name' => 'Faizabad'],
                ['id' => 122, 'name' => 'Ayodhya'],
                ['id' => 123, 'name' => 'Milkipur'],
                ['id' => 124, 'name' => 'Rudauli'],
                ['id' => 125, 'name' => 'Sohawal'],
                ['id' => 126, 'name' => 'Tanda'],
            ],
            'Farrukhabad' => [
                ['id' => 127, 'name' => 'Farrukhabad'],
                ['id' => 128, 'name' => 'Fatehgarh'],
                ['id' => 129, 'name' => 'Kamalganj'],
                ['id' => 130, 'name' => 'Naugawan Sadat'],
                ['id' => 131, 'name' => 'Aliganj'],
                ['id' => 132, 'name' => 'Raebareli'],
            ],
            'Hathras' => [
                ['id' => 133, 'name' => 'Hathras'],
                ['id' => 134, 'name' => 'Sadabad'],
                ['id' => 135, 'name' => 'Hasanpur'],
                ['id' => 136, 'name' => 'Hathras City'],
                ['id' => 137, 'name' => 'Agra'],
                ['id' => 138, 'name' => 'Mursan'],
            ],
            'Jaunpur' => [
                ['id' => 139, 'name' => 'Jaunpur'],
                ['id' => 140, 'name' => 'Machhlishahr'],
                ['id' => 141, 'name' => 'Kerakat'],
                ['id' => 142, 'name' => 'Shahganj'],
                ['id' => 143, 'name' => 'Mariyahu'],
                ['id' => 144, 'name' => 'Sujanganj'],
            ],
            'Jalaun' => [
                ['id' => 145, 'name' => 'Jalaun'],
                ['id' => 146, 'name' => 'Orai'],
                ['id' => 147, 'name' => 'Kalpi'],
                ['id' => 148, 'name' => 'Konch'],
                ['id' => 149, 'name' => 'Madhogarh'],
                ['id' => 150, 'name' => 'Auraiya'],
            ],
            'Jhansi' => [
                ['id' => 151, 'name' => 'Jhansi'],
                ['id' => 152, 'name' => 'Datia'],
                ['id' => 153, 'name' => 'Mauranipur'],
                ['id' => 154, 'name' => 'Garotha'],
                ['id' => 155, 'name' => 'Moth'],
                ['id' => 156, 'name' => 'Babina'],
            ],
            'Kanpur Dehat' => [
                ['id' => 157, 'name' => 'Kanpur Dehat'],
                ['id' => 158, 'name' => 'Akbarpur'],
                ['id' => 159, 'name' => 'Rasulpur'],
                ['id' => 160, 'name' => 'Kalyanpur'],
                ['id' => 161, 'name' => 'Sikandarpur'],
                ['id' => 162, 'name' => 'Khatima'],
            ],
            'Kanpur Nagar' => [
                ['id' => 163, 'name' => 'Kanpur Nagar'],
                ['id' => 164, 'name' => 'Kanpur South'],
                ['id' => 165, 'name' => 'Kanpur North'],
                ['id' => 166, 'name' => 'Chakeri'],
                ['id' => 167, 'name' => 'Barra'],
                ['id' => 168, 'name' => 'Kidwai Nagar'],
            ],
            'Kheri' => [
                ['id' => 169, 'name' => 'Kheri'],
                ['id' => 170, 'name' => 'Lakhimpur'],
                ['id' => 171, 'name' => 'Nighasan'],
                ['id' => 172, 'name' => 'Palia'],
                ['id' => 173, 'name' => 'Sitapur'],
                ['id' => 174, 'name' => 'Mitauli'],
            ],
            'Lucknow' => [
                ['id' => 175, 'name' => 'Lucknow'],
                ['id' => 176, 'name' => 'Malihabad'],
                ['id' => 177, 'name' => 'Sarojini Nagar'],
                ['id' => 178, 'name' => 'Mohanlalganj'],
                ['id' => 179, 'name' => 'Bakshi Ka Talab'],
                ['id' => 180, 'name' => 'Chinhat'],
            ],
            'Maharajganj' => [
                ['id' => 181, 'name' => 'Maharajganj'],
                ['id' => 182, 'name' => 'Sadar'],
                ['id' => 183, 'name' => 'Farenda'],
                ['id' => 184, 'name' => 'Paniyara'],
                ['id' => 185, 'name' => 'Kaptanganj'],
                ['id' => 186, 'name' => 'Naurangia'],
            ],
            'Mau' => [
                ['id' => 187, 'name' => 'Mau'],
                ['id' => 188, 'name' => 'Mohammadabad'],
                ['id' => 189, 'name' => 'Jamo'],
                ['id' => 190, 'name' => 'Kopaganj'],
                ['id' => 191, 'name' => 'Jhanjharpur'],
                ['id' => 192, 'name' => 'Sathiaon'],
            ],
            'Mirzapur' => [
                ['id' => 193, 'name' => 'Mirzapur'],
                ['id' => 194, 'name' => 'Lalganj'],
                ['id' => 195, 'name' => 'Chhanvey'],
                ['id' => 196, 'name' => 'Marihan'],
                ['id' => 197, 'name' => 'Pukhrayan'],
                ['id' => 198, 'name' => 'Adalhat'],
            ],
            'Moradabad' => [
                ['id' => 199, 'name' => 'Moradabad'],
                ['id' => 200, 'name' => 'Amroha'],
                ['id' => 201, 'name' => 'Chandausi'],
                ['id' => 202, 'name' => 'Bilari'],
                ['id' => 203, 'name' => 'Kanth'],
                ['id' => 204, 'name' => 'Sambhal'],
            ],
            'Muzaffarnagar' => [
                ['id' => 205, 'name' => 'Muzaffarnagar'],
                ['id' => 206, 'name' => 'Shamli'],
                ['id' => 207, 'name' => 'Khatauli'],
                ['id' => 208, 'name' => 'Budhana'],
                ['id' => 209, 'name' => 'Sardhana'],
                ['id' => 210, 'name' => 'Jansath'],
            ],
            'Pilibhit' => [
                ['id' => 211, 'name' => 'Pilibhit'],
                ['id' => 212, 'name' => 'Bisalpur'],
                ['id' => 213, 'name' => 'Puranpur'],
                ['id' => 214, 'name' => 'Bilsanda'],
                ['id' => 215, 'name' => 'Shahabad'],
                ['id' => 216, 'name' => 'Fatehganj'],
            ],
            'Pratapgarh' => [
                ['id' => 217, 'name' => 'Pratapgarh'],
                ['id' => 218, 'name' => 'Kunda'],
                ['id' => 219, 'name' => 'Bela'],
                ['id' => 220, 'name' => 'Jagdishpur'],
                ['id' => 221, 'name' => 'Lalganj'],
                ['id' => 222, 'name' => 'Koraon'],
            ],
            'Raebareli' => [
                ['id' => 223, 'name' => 'Raebareli'],
                ['id' => 224, 'name' => 'Dalmau'],
                ['id' => 225, 'name' => 'Salon'],
                ['id' => 226, 'name' => 'Rahi'],
                ['id' => 227, 'name' => 'Hilauli'],
                ['id' => 228, 'name' => 'Mahrajganj'],
            ],
            'Rampur' => [
                ['id' => 229, 'name' => 'Rampur'],
                ['id' => 230, 'name' => 'Suar'],
                ['id' => 231, 'name' => 'Jhinjhak'],
                ['id' => 232, 'name' => 'Chamraua'],
                ['id' => 233, 'name' => 'Bilaspur'],
                ['id' => 234, 'name' => 'Kichha'],
            ],
            'Saharanpur' => [
                ['id' => 235, 'name' => 'Saharanpur'],
                ['id' => 236, 'name' => 'Nakud'],
                ['id' => 237, 'name' => 'Deoband'],
                ['id' => 238, 'name' => 'Kairana'],
                ['id' => 239, 'name' => 'Shahpur'],
                ['id' => 240, 'name' => 'Gangoh'],
            ],
            'Sambhal' => [
                ['id' => 241, 'name' => 'Sambhal'],
                ['id' => 242, 'name' => 'Chandausi'],
                ['id' => 243, 'name' => 'Bhimnagar'],
                ['id' => 244, 'name' => 'Suar'],
                ['id' => 245, 'name' => 'Khimur'],
                ['id' => 246, 'name' => 'Husainpur'],
            ],
            'Shahjahanpur' => [
                ['id' => 247, 'name' => 'Shahjahanpur'],
                ['id' => 248, 'name' => 'Tilhar'],
                ['id' => 249, 'name' => 'Puranpur'],
                ['id' => 250, 'name' => 'Safaipur'],
                ['id' => 251, 'name' => 'Banda'],
                ['id' => 252, 'name' => 'Kundarki'],
            ],
            'Sitapur' => [
                ['id' => 253, 'name' => 'Sitapur'],
                ['id' => 254, 'name' => 'Laharpur'],
                ['id' => 255, 'name' => 'Biswan'],
                ['id' => 256, 'name' => 'Mau'],
                ['id' => 257, 'name' => 'Kheri'],
                ['id' => 258, 'name' => 'Sidhauli'],
            ],
            'Sonbhadra' => [
                ['id' => 259, 'name' => 'Sonbhadra'],
                ['id' => 260, 'name' => 'Obra'],
                ['id' => 261, 'name' => 'Chopan'],
                ['id' => 262, 'name' => 'Robertsganj'],
                ['id' => 263, 'name' => 'Duddhi'],
                ['id' => 264, 'name' => 'Nagwa'],
            ],
            'Sultanpur' => [
                ['id' => 265, 'name' => 'Sultanpur'],
                ['id' => 266, 'name' => 'Bhadwai'],
                ['id' => 267, 'name' => 'Musafirkhana'],
                ['id' => 268, 'name' => 'Kadipur'],
                ['id' => 269, 'name' => 'Jaisinghpur'],
                ['id' => 270, 'name' => 'Dostpur'],
            ],
            'Unnao' => [
                ['id' => 271, 'name' => 'Unnao'],
                ['id' => 272, 'name' => 'Bichhiya'],
                ['id' => 273, 'name' => 'Mohan'],
                ['id' => 274, 'name' => 'Purwa'],
                ['id' => 275, 'name' => 'Safipur'],
                ['id' => 276, 'name' => 'Bangarmau'],
            ],
            'Varanasi' => [
                ['id' => 277, 'name' => 'Varanasi'],
                ['id' => 278, 'name' => 'Kashi'],
                ['id' => 279, 'name' => 'Rohania'],
                ['id' => 280, 'name' => 'Pindra'],
                ['id' => 281, 'name' => 'Chiraigaon'],
                ['id' => 282, 'name' => 'Arajiline'],
            ],
        ];

        foreach ($tehsils as $district => $tehsilList) {
            if (isset($districts[$district])) {
                foreach ($tehsilList as $tehsil) {
                    DB::table('tehsils')->insert([
                        'id' => $tehsil['id'],
                        'name' => $tehsil['name'],
                        'district_id' => $districts[$district],
                    ]);
                }
            }
        }
    }
}
